# functions/cloudbuild.yaml
steps:
  - id: 'build-and-push-functions'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --context=dir://functions
      - --dockerfile=functions/Dockerfile
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/celesta-functions/functions:$SHORT_SHA
      - --cache=true

  - id: 'deploy-functions'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - procesador-cfes
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/celesta-functions/functions:$SHORT_SHA
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
    waitFor: ['build-and-push-functions']

options:
  logging: CLOUD_LOGGING_ONLY
