services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_USER: postgres
      DB_PASSWORD: CelestaDb2025
      DB_HOST: 10.0.0.3
      DB_PORT: 5432
      DB_DATABASE: postgres
