steps:
  # 1. Construye la imagen de Docker del backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/celesta-repo/backend:$SHORT_SHA', '.']

  # 2. Sube la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/celesta-repo/backend:$SHORT_SHA']

  # 3. Despliega la nueva imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'celesta-backend' # Este será el nombre de tu servicio en Cloud Run
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/celesta-repo/backend:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated' # ¡Importante! Permite que sea accesible públicamente