steps:
  - id: build-and-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --context=backend # <-- ¡Este es el cambio clave!
      - --dockerfile=Dockerfile # Busca el Dockerfile en el directorio actual (backend)
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/celesta-backend/api:$SHORT_SHA
      - --cache=true

  - id: deploy-to-run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud run deploy celesta-backend \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/celesta-backend/api:$SHORT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets=BIGQUERY_DATASET_ID=BIGQUERY_DATASET_ID:latest \
          --set-env-vars=BIGQUERY_TABLE_ID=cfes

options:
  logging: CLOUD_LOGGING_ONLY
